font_family      Fira Code Nerd Font
font_size        12.0


# The basic colors
# background           #282a36
# foreground           #f8f8f2
# cursor               #f8f8f2
# selection_background #44475a
# selection_foreground #f8f8f2
# The black and white colors
# color0               #000000
# color8               #4d4d4d
# The 16 terminal colors
# color1  #ff5555
# color2  #50fa7b
# color3  #f1fa8c
# color4  #bd93f9
# color5  #ff79c6
# color6  #8be9fd
# color7  #f8f8f2
# color9  #ff6e67
# color10 #5af78e
# color11 #f4f99d
# color12 #caa9fa
# color13 #ff92d0
# color14 #8bedfd
# color15 #eff0eb

# Open a new tab
map kitty_mod+t new_tab
# Close the current tab
map kitty_mod+w close_tab
# Toggle fullscreen mode
map kitty_mod+f toggle_fullscreen

# Adjust padding around the terminal
# padding 5 5 5 5
# Adjust window opacity
# background_opacity 0.95


# Switch to the next window
map ctrl+shift+n next_window
# Switch to the previous window
map ctrl+shift+p previous_window
# Move active window to next layout
map ctrl+shift+l next_layout
# Create new window with the same working directory
map ctrl+shift+enter new_window_with_cwd
# Close the current window
map ctrl+shift+w close_window

# Copy to clipboard
map ctrl+shift+c copy_to_clipboard
# Paste from clipboard
map ctrl+shift+v paste_from_clipboard

scrollback_lines 10000

# hints
map ctrl+shift+e kitten hints


# BEGIN_KITTY_THEME
# Atelier Forest Dark
include current-theme.conf
# END_KITTY_THEME
