
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Move the prompt to a new line
add_newline = true

# The order of modules
format = """
[░▒▓](#7aa2f7)\
[ ⛩️  ]($style)\
[▓▒░](#7aa2f7)\
$directory\
$git_branch\
$git_status\
$package\
$golang\
$rust\
$node\
$python\
$line_break\
$character"""

# A separate line for the right side (optional)
right_format = """$cmd_duration $time"""

[character]
success_symbol = "[道](bold green) " # Japanese for "The Way/Path"
error_symbol = "[×](bold red) "
vimcmd_symbol = "[N](bold blue) "

[directory]
style = "bg:#3b4252 fg:#e5e9f0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bg:#3b4252 fg:#7aa2f7"
# Use single quotes here
format = '[[ $symbol $branch ](fg:#7aa2f7 bg:#3b4252)]($style)'

[git_status]
style = "bg:#3b4252 fg:#7aa2f7"
# Use single quotes here to protect the parentheses
format = '[[($all_status$ahead_behind )](fg:#7aa2f7 bg:#3b4252)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "dimmed white"
format = '[  $time ]($style)'

[cmd_duration]
min_time = 500
format = "[ $duration ]($style)"
style = "yellow"

[package]
symbol = "󰏗 "

[python]
symbol = " "
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "bold green"

[rust]
symbol = " "

[nodejs]
symbol = " "
format = '[[ $symbol ($version) ]($style)]'
style = "bg:#7aa2f7 fg:#1a1b26" # Matching your Tokyo Night theme

[golang]
symbol = " "
